### PR TITLE
New animal breed added

### PR DESCRIPTION
**Pull request by MichaelKobin**
Hey team lead Kseniia, I had added a class for your review
it includes all the function of this animal

Thank you!

### CODE REVIEW

**Comment by KseniiaKr** [comment]
I don't know if this is the kind of  animal we would like to keep in our Zoo. I need other opinions to make a decision. Ladies, would do you think? Merge or delete?

**Review by KseniiaKr — CHANGES_REQUESTED** [review]
the animal is too aggressive, needs to be more end-user friendly

**Comment by MichaelKobin** [comment]
it's a backend animal 😁

________________________________

**Review by elvirka7 — CHANGES_REQUESTED** [review]
are you worried its gonna get you?

**Pull request closed without merging**
